<?php
module_load_include('inc', 'node_list', 'node_list.admin');

/*
 * hook menu
 */
function node_list_menu(){
	$items['node_list'] = array(
		'title' => 'Node List',
		'page callback' => 'list_all',
		'access callback' => TRUE,
	);
	return $items;
}

/*
 * List function, funcion de listado
 */
function list_all(){
	//Look for nodes in the table we want to show
	$result = db_select('node_list_table', 'nl')
			    ->fields('nl')
			    ->execute();
	
	//Save nodes id in a table for use like condition on next query
	$showing_nodes = array();
	$showing_nodes[] = ''; //at least one valor for no get an error on the next search
	while($node_type = $result->fetchAssoc()) {
        $showing_nodes[] = $node_type['node_type'];
    }
	
	//Search in node table looking for equivalences
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
		  ->propertyCondition('type', $showing_nodes, 'IN');
	$result = $query->execute();
	
	if (isset($result['node'])) {
  		$nodes = array_keys($result['node']);
  		$nodes = entity_load('node', $nodes);
	}
	
	//Now we list all nodes for show it
	$list = array();
	$n = 0;
	if(isset($nodes) && count($nodes) > 0){
		foreach($nodes as $node){
			$list[$n]['title'] = $node->title;
			$list[$n]['type'] = $node->type;
			$n++;
		}
	}
	else
		$list[$n] = "No elements to show";
	
	$var = array('var' => $list);
	return theme('list_all', $var);
}

/*
 * Template function
 */
function node_list_theme(){
	return array(
		'list_all' => array(
			'template' => 'node-list',
		),
	);
}
?>